# Generated by Django 5.2.14 on 2026-05-07 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='dept_name',
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hod_name', models.CharField(max_length=100)),
                ('detailss', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='hod_photos/')),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hods', to='sins.department')),
            ],
        ),
    ]
