# Generated by Django 5.2.14 on 2026-05-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0002_rename_name_department_dept_name_hod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hod',
            old_name='dept_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='Hod_name',
        ),
        migrations.AlterField(
            model_name='department',
            name='details',
            field=models.CharField(),
        ),
    ]
