# Generated by Django 5.2.14 on 2026-05-07 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0003_rename_dept_name_department_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hod',
            old_name='name',
            new_name='department',
        ),
    ]
