# Generated by Django 5.2.14 on 2026-05-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0004_rename_name_hod_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='details',
            field=models.CharField(max_length=255),
        ),
    ]
